### PR TITLE
Add WireGuard via manifest

### PR DESCRIPTION
**Pull request by zx2c4**
This is a superior technique to using patcher. More information may be found at: https://git.zx2c4.com/android_kernel_wireguard/about/.

Please merge this immediately before https://github.com/sultanxda/patcher/pull/11.

### CODE REVIEW

**Comment by ttimasdf** [comment]
Get following error after updated manifest.
```
Fetching project android_kernel_wireguard/wireguard
error: no such remote ref e4b7fec69135ecc50b3a105fbf09efc9e037e113
error: Cannot fetch android_kernel_wireguard/wireguard
```
Possibly because of a forced push.

**Comment by ttimasdf** [comment]
I make a conclusion of what I've recently discovered.

First of all, the error above was fired by command `git fetch --progress --depth=1 zx2c4 --no-tags e4b7fec69135ecc50b3a105fbf09efc9e037e113`, but `git submodule update` works well and the commit hash actually exists.
After inspecting the [git-repo code](https://github.com/esrlabs/git-repo/blob/5f859ebb0a2a3dc290adfb638541b5559925d002/project.py#L1734), `repo` command internally grab the SHA sum of submodule object and use it as refspec in git fetch. 
However, the Git [documentation](https://git-scm.com/book/en/v2/Git-Internals-The-Refspec) didn't mention a way to use shasum for fetching. so `git fetch` will just fail.

In a word, `repo` command currently cannot correctly handle recursive submodule downloading, nor do AOSP manifest use `sync-s` parameter anywhere. Do you have any ideas or working environment (OS, git version, etc.) at least? @zx2c4 @sultanxda

**Comment by zx2c4** [comment]
Thanks. I'm researching and I'll have a fix soon.

**Comment by zx2c4** [comment]
I moved away from submodules. Indeed repo has rotted and it doesn't work properly. The new solution should save some bandwidth too.

Try syncing and running @ttimasdf.

The proper venue, by the way, for discussing this is [the wireguard mailing list](https://lists.zx2c4.com/mailman/listinfo/wireguard).

**Comment by ttimasdf** [comment]
Oh, thanks. I've been getting used to mailing list, made a subscription request.

**Pull request merged**
